# Generated by Django 3.0.5 on 2020-11-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albuminfo',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albuminfo',
            old_name='album_id',
            new_name='albumid',
        ),
        migrations.RenameField(
            model_name='songinfo',
            old_name='song_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='songinfo',
            old_name='picture',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='songinfo',
            old_name='song_id',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='songinfo',
            old_name='total_time',
            new_name='songTimeMinutes',
        ),
    ]
