# Generated by Django 3.0.5 on 2020-11-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20201106_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songinfo',
            old_name='singer',
            new_name='artist',
        ),
    ]
