# Generated by Django 3.0.5 on 2020-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/j.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
