# Generated by Django 3.0.5 on 2020-11-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('total_time', models.CharField(max_length=50)),
                ('song_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.SongInfo')),
            ],
        ),
    ]
