# Generated by Django 3.0.5 on 2020-11-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20201106_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumInfo',
        ),
        migrations.DeleteModel(
            name='SongInfo',
        ),
    ]
