# Generated by Django 3.0.5 on 2020-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(default='', max_length=50, verbose_name='来源url')),
                ('company_name', models.CharField(default='', max_length=20, verbose_name='公司名称')),
                ('linkman', models.CharField(default='', max_length=10, verbose_name='联系人')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('create_user', models.CharField(default='', max_length=10, verbose_name='创建者')),
                ('create_date', models.CharField(default='', max_length=20, verbose_name='创建时间')),
                ('version', models.CharField(default=0, max_length=10, verbose_name='版本')),
                ('is_deleted', models.CharField(default=0, max_length=10, verbose_name='是否删除')),
                ('is_repeat', models.CharField(default=0, max_length=10, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'ordering': ['company_name'],
            },
        ),
    ]
